#!/bin/bash

exit_status=0
gemfile_dir=$1
gemfile="$gemfile_dir/Gemfile"
scenarios=$(cat $gemfile_dir/scenarios)

function run_scenario {
  test_scenario=$1

  echo
  echo "Testing scenario $scenario with $gemfile..."
  export BUNDLE_GEMFILE=$gemfile
  bundle install
  result="$(bundle exec ruby -I lib ${test_scenario})"

  status=$?
  if [[ $result != "" ]]; then
    echo
    echo "=> FAIL: Expected empty output but was:"
    echo "--$result--"
    return 1
  fi
  if [[ $status -ne 0 ]]; then
    echo
    echo "=> FAIL: Expected zero exit status"
    return 1
  fi
  echo "=> PASS"
}

echo $scenarios
for scenario in $scenarios; do
  run_scenario "test/scenarios/$scenario"
  if [ $? -ne 0 ]; then
      exit_status=1
  fi
done

exit "$exit_status"
